let SLIDER = [
    { 
        id: 1, 
        title: "ipsum dolor",
        header: "Lorem ipsum",
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Ipsum optio eveniet odio?",
        img: "./images/slider/slide-img-1.jpg",
    },
    { 
        id: 2, 
        title: "ipsum dolor",
        header: "Lorem ipsum",
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Ipsum optio eveniet odio?",
        img: "./images/slider/slide-img-2.jpg",
    },
    { 
        id: 3,
        title: "ipsum dolor",
        header: "Lorem ipsum",
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Ipsum optio eveniet odio?",
        img: "./images/slider/slide-img-3.jpg",
    },
    { 
        id: 4, 
        title: "ipsum dolor",
        header: "Lorem ipsum",
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Ipsum optio eveniet odio?",
        img: "./images/slider/slide-img-4.jpg",
    },
];


let CATEGORIES = [
    { 
        id: 1, 
        name: "LAPTOP",
        img: `./images/categories/category-img-1.jpg`,
    },
    { 
        id: 2, 
        name: "WATCH",
        img: `./images/categories/category-img-2.jpg`,
    },
    { 
        id: 3,
        name: "KEYBOARDS",
        img: `./images/categories/category-img-3.jpg`,
    },
    { 
        id: 4, 
        name: "HEADPHONE",
        img: `./images/categories/category-img-4.jpg`,
    },
    { 
        id: 5, 
        name: "CAMERE",
        img: `./images/categories/category-img-5.jpg`,
    },
    { 
        id: 6, 
        name: "PHONE",
        img: `./images/categories/category-img-6.jpg`,
    },
];

let USERS = [
    {
        id: 1,
        username: "nhd",
        password: "123",
        isAdmin: true,
        cart: [
            {
                item: {
                    id: 1,
                    name: "MSI1",
                    price: 100000,
                    category: "Laptop",
                    rate: 5,
                },
                amount: 2,
            },
            {
                item: {
                    id: 2,
                    name: "PC1",
                    price: 200000,
                    category: "PC",
                    rate: 4,
                },
                amount: 1,
            },
        ],
    },
    {
        id: 2,
        username: "cpt",
        password: "123",
        isAdmin: true,
        cart: [
            {
                item: {
                    id: 1,
                    name: "MSI1",
                    price: 100000,
                    category: "Laptop",
                    rate: 5,
                },
                amount: 2,
            },
            {
                item: {
                    id: 2,
                    name: "PC1",
                    price: 200000,
                    category: "PC",
                    rate: 4,
                },
                amount: 1,
            },
        ],
    },
    {
        id: 3,
        username: "lct",
        password: "123",
        isAdmin: true,
        cart: [
            {
                item: {
                    id: 1,
                    name: "MSI1",
                    price: 100000,
                    category: "Laptop",
                    rate: 5,
                },
                amount: 2,
            },
            {
                item: {
                    id: 2,
                    name: "PC1",
                    price: 200000,
                    category: "PC",
                    rate: 4,
                },
                amount: 1,
            },
        ],
    },
    {
        id: 4,
        username: "npt",
        password: "123",
        isAdmin: true,
        cart: [
            {
                item: {
                    id: 1,
                    name: "MSI1",
                    price: 100000,
                    category: "Laptop",
                    rate: 5,
                },
                amount: 2,
            },
            {
                item: {
                    id: 2,
                    name: "PC1",
                    price: 200000,
                    category: "PC",
                    rate: 4,
                },
                amount: 1,
            },
        ],
    },
    {
        id: 5,
        username: "client",
        password: "123",
        isAdmin: false,
        cart: [
            {
                item: {
                    id: 1,
                    name: "MSI1",
                    price: 100000,
                    category: "Laptop",
                    rate: 5,
                },
                amount: 2,
            },
            {
                item: {
                    id: 2,
                    name: "PC1",
                    price: 200000,
                    category: "PC",
                    rate: 4,
                },
                amount: 1,
            },
        ],
    },
];

let PRODUCTS = [
    {
        id: 1, 
        name: "IPHONE 13 9", 
        sale: '189.00$',
        price: 100000, 
        category: "Laptop", 
        rate: 5,
        wish: 0,
        imgList: [
            "./images/products/product-1-img-1.jpg",
            "./images/products/product-1-img-2.jpg",
        ],
    },
    {
        id: 2, 
        name: "IPHONE 13 1", 
        sale: '189.00$',
        price: 100000, 
        category: "Laptop", 
        rate: 5,
        wish: 0,
        imgList: [
            "./images/products/product-2-img-1.jpg",
            "./images/products/product-2-img-2.jpg",
        ],
    },
    {
        id: 3, 
        name: "IPHONE 13 2", 
        sale: '189.00$',
        price: 100000, 
        category: "Laptop", 
        rate: 5,
        wish: 0,
        imgList: [
            "./images/products/product-3-img-1.jpg",
            "./images/products/product-3-img-2.jpg",
        ],
    },
    {
        id: 4, 
        name: "IPHONE 13 3", 
        sale: '189.00$',
        price: 100000, 
        category: "Laptop", 
        rate: 5,
        wish: 0,
        imgList: [
            "./images/products/product-4-img-1.jpg",
            "./images/products/product-4-img-2.jpg",
        ],
    },
    {
        id: 5, 
        name: "IPHONE 13 4", 
        sale: '189.00$',
        price: 100000, 
        category: "Laptop", 
        rate: 5,
        wish: 0,
        imgList: [
            "./images/products/product-5-img-1.jpg",
            "./images/products/product-5-img-2.jpg",
        ],
    },
    {
        id: 6, 
        name: "IPHONE 13 5", 
        sale: '189.00$',
        price: 100000, 
        category: "Laptop", 
        rate: 5,
        wish: 0,
        imgList: [
            "./images/products/product-6-img-1.jpg",
            "./images/products/product-6-img-2.jpg",
        ],
    },
    {
        id: 7, 
        name: "IPHONE 13 6", 
        sale: '189.00$',
        price: 100000, 
        category: "Laptop", 
        rate: 5,
        wish: 0,
        imgList: [
            "./images/products/product-7-img-1.jpg",
            "./images/products/product-7-img-2.jpg",
        ],
    },
    {
        id: 8, 
        name: "IPHONE 13 7", 
        sale: '189.00$',
        price: 100000, 
        category: "Laptop", 
        rate: 5,
        wish: 0,
        imgList: [
            "./images/products/product-8-img-1.jpg",
            "./images/products/product-8-img-2.jpg",
        ],
    },
    {
        id: 9, 
        name: "IPHONE 13 9", 
        sale: '189.00$',
        price: 100000, 
        category: "Laptop", 
        rate: 5,
        wish: 0,
        imgList: [
            "./images/products/product-1-img-1.jpg",
            "./images/products/product-1-img-2.jpg",
        ],
    },
    {
        id: 10, 
        name: "IPHONE 13 1", 
        sale: '189.00$',
        price: 100000, 
        category: "Laptop", 
        rate: 5,
        wish: 0,
        imgList: [
            "./images/products/product-2-img-1.jpg",
            "./images/products/product-2-img-2.jpg",
        ],
    },
    {
        id: 11, 
        name: "IPHONE 13 2", 
        sale: '189.00$',
        price: 100000, 
        category: "Laptop", 
        rate: 5,
        wish: 0,
        imgList: [
            "./images/products/product-3-img-1.jpg",
            "./images/products/product-3-img-2.jpg",
        ],
    },
    {
        id: 12, 
        name: "IPHONE 13 3", 
        sale: '189.00$',
        price: 100000, 
        category: "Laptop", 
        rate: 5,
        wish: 0,
        imgList: [
            "./images/products/product-4-img-1.jpg",
            "./images/products/product-4-img-2.jpg",
        ],
    },
    {
        id: 13, 
        name: "IPHONE 13 4", 
        sale: '189.00$',
        price: 100000, 
        category: "Laptop", 
        rate: 5,
        wish: 0,
        imgList: [
            "./images/products/product-5-img-1.jpg",
            "./images/products/product-5-img-2.jpg",
        ],
    },
    {
        id: 14, 
        name: "IPHONE 13 5", 
        sale: '189.00$',
        price: 100000, 
        category: "Laptop", 
        rate: 5,
        wish: 0,
        imgList: [
            "./images/products/product-6-img-1.jpg",
            "./images/products/product-6-img-2.jpg",
        ],
    },
    {
        id: 15, 
        name: "IPHONE 13 6", 
        sale: '189.00$',
        price: 100000, 
        category: "Laptop", 
        rate: 5,
        wish: 0,
        imgList: [
            "./images/products/product-7-img-1.jpg",
            "./images/products/product-7-img-2.jpg",
        ],
    },
    {
        id: 16, 
        name: "IPHONE 13 7", 
        sale: '189.00$',
        price: 100000, 
        category: "Laptop", 
        rate: 5,
        wish: 0,
        imgList: [
            "./images/products/product-8-img-1.jpg",
            "./images/products/product-8-img-2.jpg",
        ],
    },
    {
        id: 17, 
        name: "IPHONE 13 9", 
        sale: '189.00$',
        price: 100000, 
        category: "Laptop", 
        rate: 5,
        wish: 0,
        imgList: [
            "./images/products/product-1-img-1.jpg",
            "./images/products/product-1-img-2.jpg",
        ],
    },
    {
        id: 18, 
        name: "IPHONE 13 1", 
        sale: '189.00$',
        price: 100000, 
        category: "Laptop", 
        rate: 5,
        wish: 0,
        imgList: [
            "./images/products/product-2-img-1.jpg",
            "./images/products/product-2-img-2.jpg",
        ],
    },
    {
        id: 19, 
        name: "IPHONE 13 2", 
        sale: '189.00$',
        price: 100000, 
        category: "Laptop", 
        rate: 5,
        wish: 0,
        imgList: [
            "./images/products/product-3-img-1.jpg",
            "./images/products/product-3-img-2.jpg",
        ],
    },
    {
        id: 20, 
        name: "IPHONE 13 3", 
        sale: '189.00$',
        price: 100000, 
        category: "Laptop", 
        rate: 5,
        wish: 0,
        imgList: [
            "./images/products/product-4-img-1.jpg",
            "./images/products/product-4-img-2.jpg",
        ],
    },
    {
        id: 21, 
        name: "IPHONE 13 4", 
        sale: '189.00$',
        price: 100000, 
        category: "Laptop", 
        rate: 5,
        wish: 0,
        imgList: [
            "./images/products/product-5-img-1.jpg",
            "./images/products/product-5-img-2.jpg",
        ],
    },
    {
        id: 23, 
        name: "IPHONE 13 5", 
        sale: '189.00$',
        price: 100000, 
        category: "Laptop", 
        rate: 5,
        wish: 0,
        imgList: [
            "./images/products/product-6-img-1.jpg",
            "./images/products/product-6-img-2.jpg",
        ],
    },
    {
        id: 24, 
        name: "IPHONE 13 6", 
        sale: '189.00$',
        price: 100000, 
        category: "Laptop", 
        rate: 5,
        wish: 0,
        imgList: [
            "./images/products/product-7-img-1.jpg",
            "./images/products/product-7-img-2.jpg",
        ],
    },
    {
        id: 25, 
        name: "IPHONE 13 7", 
        sale: '189.00$',
        price: 100000, 
        category: "Laptop", 
        rate: 5,
        wish: 0,
        imgList: [
            "./images/products/product-8-img-1.jpg",
            "./images/products/product-8-img-2.jpg",
        ],
    },
];